### ISSUE TITLE
[Request] Add snytax highlighting to MSIAfterburner.dll Plugin

### ISSUE THREAD

**Issue by Aethrios** [thatsIch/sublime-rainmeter#44]
Hey ya'll, apologies if this is the wrong place to drop this (it's the only link offered through Sublime, so I thought it might still be relevant).

I wanted to put in a request for the addition of syntax highlighting for the MSIAfterburner.dll plugin. An example/usage:

[MeasureGPUTemp]
Measure=Plugin (this works fine)
Plugin=MSIAfterburner.dll
DataSource=GPU temperature

DataSource can call any of the following values, which include the spaces, and are case sensitive:

GPU voltage
Core clock
Shader clock
Memory clock
Framerate
GPU usage
GPU temperature
PCB temperature
Fan speed
Fan tachometer

Pretty much, any data source that the actual MSI Afterburner application can produce and track, the corresponding plugin in Rainmeter can call. Those listed above are the ones I was able to source, and I'm not sure if any of the other, more obscure options would be tracked.

Thanks for reading!

**Comment by thatsIch** [comment]
Cheers,

please test the latest build on https://ci.appveyor.com/project/thatsIch/sublime-rainmeter/branch/master
I will release it, after you have tested it. I did not add auto-completion for it, since it is a third-party plugin. The result looks like this

![msi-shaded-or8](https://cloud.githubusercontent.com/assets/2210496/25203730/98045ed8-255a-11e7-82fc-8ad42de95559.png)

I rely on the information you provided, 


have a nice day 😃

**Comment by Aethrios** [comment]
Thanks for such a quick response (and apologies for my own slowness, I don't check up on github as frequently as perhaps I should!)

This looks great, thanks again for all your hard work. You made the transition to sublime pretty seamless for me!
